development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:c6883eda480d8763146fbec573389fdf@pearlfish.redistogo.com:9631/
  channel_prefix: Flack_production
